Update monitor.yml

diff --git a/.github/workflows/monitor.yml b/.github/workflows/monitor.yml
--- a/.github/workflows/monitor.yml
+++ b/.github/workflows/monitor.yml
@@ -1,20 +1,21 @@
-name: Monitor
+name: Monitor Application
 
 on:
-  # Kích hoạt khi có push lên các nhánh cụ thể
-  push:
-  # Kích hoạt tự động theo lịch trình
   schedule:
-    - cron: '* * * * *' # Chạy mỗi 15 phút
+    - cron: '*/2 * * * *'  # Chạy mỗi 1 phút (cron syntax)
 
 jobs:
-  ping_site:
+  monitor:
     runs-on: ubuntu-latest
-    name: Ping the site
+
     steps:
-    - name: Check the site
-      id: hello
-      uses: srt32/uptime@master
-      with:
-        url-to-hit: "https://flightdotapi.azurewebsites.net/health"
-        expected-statuses: "200"
+      - name: Check API Health
+        run: |
+          echo "Checking health at ${{ env.HEALTH_CHECK_URL }}"
+          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.HEALTH_CHECK_URL }})
+          if [ "$response" -eq 200 ]; then
+            echo "Health check passed!"
+          else
+            echo "Health check failed!"
+            exit 1
+          fi
